version: '3.7'

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=admin
      - PASS=admin
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    volumes:
      - /mnt/storage/transmission/config:/config
      - /mnt/storage/incomplete-downloads:/downloads
      - /mnt/storage/downloads:/downloads/complete
    restart: unless-stopped

  telebotardo-transmission:
    build:
      context: .
    restart: unless-stopped
    network_mode: 'host'
    depends_on:
      - transmission

  plex:
    image: jaymoulin/plex:latest
    volumes:
      - /mnt/storage/tmp:/tmp
      - /mnt/storage/downloads:/media
      - /mnt/storage/plex:/root/Library/Application Support/Plex Media Server
    restart: unless-stopped
    network_mode: 'host'
