version: '3.7'

services:
  transmission:
    container_name: transmission
    image: jaymoulin/transmission:latest
    command: transmission-daemon -f -g /config
    volumes:
      - /mnt/storage/transmission/config:/config
      - /mnt/storage/downloads:/downloads/complete
    environment:
      - WEB_PASSWD=admin
      - TRANSMISSION_USER=admin
      - TRANSMISSION_PASSWORD=admin
    hostname: 'transmission'
    restart: unless-stopped
    network_mode: 'host'

  telebotardo-transmission:
    build:
      context: .
    restart: unless-stopped
    network_mode: 'host'
    depends_on:
      - transmission

  plex:
    image: jaymoulin/plex:latest
    volumes:
      - /mnt/storage/tmp:/tmp
      - /mnt/storage/downloads:/media
      - /mnt/storage/plex:/root/Library/Application Support/Plex Media Server
    restart: unless-stopped
    network_mode: 'host'
